### ISSUE TITLE
HTML code is not valid

### ISSUE THREAD

**Issue by hrniels** [script-solution/Boardsolution#26]
See [here](http://www.script-solution.de/index.php?action=userprofile&sub=pmoverview&option=com_joobs&Itemid=26&lang=de).

**Comment by Rafioso** [comment]
The link in the starting-post is not related to the support-board. It's related for every BS-Install with following URL-String: `action=userprofile&sub=pmoverview&option=com_joobs&Itemid=26&lang=de`

But maybe this was fixed in a later version.
