### ISSUE TITLE
One can set 0 days for the ip-log

### ISSUE THREAD

**Issue by hrniels** [script-solution/Boardsolution#27]
See [here](http://www.script-solution.de/index.php?action=redirect&loc=show_post&id=23017&Itemid=26&option=com_joobs).

**Comment by Rafioso** [comment]
Link down. Here is the original text of the linked post:
>hm, ok, man kann den IP-Log-Zeitraum auch auf 0 Tage stellen, jedoch nimmt der Task darauf keine
>Rücksicht.
>Änder mal die Zeilen 164,165 der src/dao/logips.php:
>
>`if(!FWS_Helper::is_integer($timeout) || $timeout <= 0)
>  FWS_Helper::def_error('intgt0','timeout',$timeout);`
>
>in:
>
>`if(!FWS_Helper::is_integer($timeout) || $timeout < 0)
>  FWS_Helper::def_error('intge0','timeout',$timeout);`
>
>Dann funktioniert es auch mit 0 Tagen, wobei dann einfach immer alle gelöscht werden. Es heißt also
>nicht, dass nichts gespeichert wird, sondern nur, dass der Task jedes mal alles löscht.
>
>mfg Nils
