### ISSUE TITLE
Save date for the max-user-online stats

### ISSUE THREAD

**Issue by hrniels** [script-solution/Boardsolution#36]

**Comment by Rafioso** [comment]
Since some years ago after you open this issue, can you please explain with an example, what you mean?

**Comment by hrniels** [comment]
No, sorry, too long ago.

**Comment by Rafioso** [comment]
I thing something like that: Save the date, when the "max user online" in stats was reached.

**Comment by hrniels** [comment]
Ah, stimmt, das wirds sein. Also zu den Statistiken ein "die maximale Anzahl von Usern war online am DD.MM.YYYY" hinzufügen.
