### ISSUE TITLE
[installation] Make the board-url validation less strict

### ISSUE THREAD

**Issue by hrniels** [script-solution/Boardsolution#52]
At least, http and https should be allowed. (see http://www.script-solution.de/community/support-board/posts_36_4259_1.html#b_23628)

**Comment by Rafioso** [comment]
Link down. Here is the original text of the linked post:

>>ckragt hat folgendes geschrieben:
>>Der Pfad lautet https://www.domain.tld/forum
>
>Ah, ok. Es liegt daran, dass nur http:// bei der Installation als gültig gilt. Das sollte ich mal
>ändern. Ansonsten dürfte https keine Probleme machen. Du kannst das umgehen indem du Zeile 88,89
>der install/module/3/helper.php:
>`      $check['board_url'] = FWS_String::substr($board_url,0,7) == "http://" &&
>      $board_url[FWS_String::strlen($board_url) - 1] != '/';`
>
>z.B. in:
>
>`      $check['board_url'] = FWS_String::substr($board_url,0,8) == "https://" &&
>      $board_url[FWS_String::strlen($board_url) - 1] != '/';`
>
>änderst.
>
>mfg Nils
