### ISSUE TITLE
Delete email-notification-entries if posts are deleted.

### ISSUE THREAD

**Issue by hrniels** [script-solution/Boardsolution#63]
There are multiple situations where this is necessary (deleting posts, deleting topics, ...).
See also: http://www.script-solution.de/community/support-board/posts_36_4265_1.html#b_23675

**Comment by Rafioso** [comment]
Link down. Here is the original text of the linked post:

>Hallo,
>
>ich habe einmal nachgeguckt was es sein könnte. Der Fehler tritt auf, wenn ein Beitrag gelöscht
>wird, zu dem noch E-Mail-Benachrichtigungen verschickt werden sollten. Um das zu beheben reicht es
>erstmal unter Zeile 51 der src/tasks/email_notification.php:
>
>  `$pdata = BS_DAO::get_posts()->get_post_by_id($row['post_id']);`
>
>folgendes einzufügen:
>
>  `if($pdata === false)
>  continue;`
>
>Eigentlich sollten die Einträge in unsent_posts aber beim Löschen von Beiträgen entfernt werden.
>Werd ich mir notieren.
>
>mfg Nils
