### ISSUE TITLE
action=posts with invalid forum-id leads to internal error

### ISSUE THREAD

**Issue by hrniels** [script-solution/Boardsolution#9]
See [here](http://www.script-solution.de/community/support-board/index.php?action=posts&fid=36&tid=4114&site=1&option=com_joobs&Itemid=26&lang=de#b_22681).

**Comment by Rafioso** [comment]
Link down. Here is the original text of the linked post:

> Hi,
>
>passend dazu:
>Zitat:
>Fehlermeldung: 256: The argument $id (value = "NULL";) has to be an
>integer and > 0
>Anfrage:
>/index.php?tid=933&amp;site=5&amp;sid=3cefbd1cf49ac2e371eb94eac27ef07b&amp;action=posts&amp;fid=51%2
>5%27%20aND%20%278%25%27%3D%278
>Backtrace:
>
>    /fws/error/handler.php, 192 [FWS_Error_Handler::get_error_message()]
>    Unknown [FWS_Error_Handler::handle_error()]
>    /fws/helper.php, 291 [trigger_error()]
>    /fws/helper.php, 246 [FWS_Helper::error()]
>    /fws/tree/manager.php, 385 [FWS_Helper::def_error()]
>    /fws/tree/manager.php, 401 [FWS_Tree_Manager::get_node()]
>    /src/functions.php, 35 [FWS_Tree_Manager::get_node_data()]
>    /src/auth.php, 675 [BS_Functions::has_access_to_intern_forum()]
>    /front/module/posts/module.php, 44 [BS_Auth::has_access_to_intern_forum()]
>    /fws/document.php, 479 [BS_Front_Module_posts::init()]
>    /src/document.php, 66 [FWS_Document::prepare_rendering()]
>    /front/src/document.php, 63 [BS_Document::prepare_rendering()]
>    /fws/document.php, 440 [BS_Front_Document::prepare_rendering()]
>    /index.php, 73 [FWS_Document::render()]
>
>Wird nur von Gästen ausgelöst.
>
>Da versuchte wohl jemand SQL-Injections auszuführen...
>
>PS: Die Darstellung der Sonderzeichen bei "Anfrage:" könnte man vll. auch noch überarbeiten.
>PPS: Vll. den Threadtitel hier etwas abändern.
>
>MfG
>Rafioso
