### ISSUE TITLE
Use SSL based call to proceed vcompare

### ISSUE THREAD

**Issue by marcel-liebgott** [script-solution/Boardsolution#90]
If you executed the "Alle Änderungen downloaden" action inside the vcompare acp module from a https signed page you get an CORS error

**Comment by Rafioso** [comment]
I think, the problem is that the comparing-part receives data from a not secure source.
Maybe it helps, to set the source to https? The domain is certified anyway, so why not?

**Comment by hrniels** [comment]
Yes, we should do that via https in the next version.

**Comment by Rafioso** [comment]
Not necessary anymore.
